services:
  # Ekkalavya Sports AI - Main Application
  - type: web
    name: ekkalavya-sports-ai
    env: node
    plan: starter
    region: ohio
    buildCommand: |
      npm install --include=dev
      npx vite build
      npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist
    startCommand: npm run start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: ekkalavya-sports-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: REPLIT_DOMAINS
        value: ekkalavya-sports-ai.onrender.com
      - key: ISSUER_URL
        value: https://replit.com/oidc
      - key: REPL_ID
        sync: false

  # AI Analysis Backend Service
  - type: web
    name: ekkalavya-ai-backend
    env: python
    plan: standard
    region: ohio
    buildCommand: |
      pip install --upgrade pip
      pip install --no-cache-dir --upgrade typing-extensions
      pip install --no-cache-dir fastapi==0.104.1 uvicorn[standard]==0.24.0 python-multipart pydantic==2.5.0
      pip install --no-cache-dir opencv-python-headless mediapipe==0.10.8 numpy==1.24.4 scipy==1.11.4
      pip install --no-cache-dir tensorflow==2.13.0 scikit-learn==1.3.2
      pip install --no-cache-dir pandas==2.1.4 Pillow==10.1.0 aiofiles websockets==12.0
    startCommand: cd ai_backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "2"

databases:
  - name: ekkalavya-sports-db
    databaseName: ekkalavya_sports_ai
    user: ekkalavya_user
    plan: free
    region: ohio