services:
  # Ekkalavya Sports AI - Main Application
  - type: web
    name: ekkalavya-sports-ai
    env: node
    plan: starter
    region: ohio
    buildCommand: |
      npm install --include=dev
      npx vite build
      npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist
    startCommand: npm run start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: ekkalavya-sports-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: REPLIT_DOMAINS
        value: ekkalavya-sports-ai.onrender.com
      - key: ISSUER_URL
        value: https://replit.com/oidc
      - key: REPL_ID
        sync: false

  # AI Analysis Backend Service
  - type: web
    name: ekkalavya-ai-backend
    env: python
    plan: starter
    region: ohio
    buildCommand: |
      pip install --upgrade pip
      pip install fastapi uvicorn[standard] python-multipart pydantic
      pip install opencv-python mediapipe numpy scipy
      pip install tensorflow torch torchvision scikit-learn
      pip install ahrs filterpy scikit-image pandas matplotlib seaborn plotly
      pip install Pillow imageio librosa soundfile xgboost lightgbm
      pip install albumentations aiofiles websockets structlog
    startCommand: python start_ai_backend.py
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHONPATH
        value: /opt/render/project/src

databases:
  - name: ekkalavya-sports-db
    databaseName: ekkalavya_sports_ai
    user: ekkalavya_user
    plan: free
    region: ohio