name: ekkalavya_sports_ai
description: A comprehensive sports training platform with AI-powered analysis

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  
  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # Navigation
  go_router: ^12.1.1
  
  # HTTP & WebSocket
  http: ^1.1.0
  web_socket_channel: ^2.4.0
  dio: ^5.3.2
  
  # Camera & Video
  camera: ^0.10.5+5
  video_player: ^2.7.2
  image_picker: ^1.0.4
  
  # AR & Computer Vision - ESSENTIAL for AR analysis
  # arcore_flutter_plugin: ^0.1.0
  ar_flutter_plugin_updated: ^0.0.1
  arkit_plugin: ^1.1.2
  
  # Unity AR Integration - PRODUCTION READY
  flutter_unity_widget: ^2022.2.0
  
  # File Handling
  file_picker: ^8.0.0+1
  path_provider: ^2.1.1
  
  # Authentication
  flutter_secure_storage: ^9.0.0
  
  # Charts & Analytics
  fl_chart: ^0.64.0
  syncfusion_flutter_charts: ^23.1.36
  
  # Utilities
  intl: ^0.18.1
  uuid: ^4.0.0
  permission_handler: ^11.0.1
  equatable: ^2.0.7
  vector_math: ^2.1.4
  
  # Real-time Communication - ESSENTIAL for live data
  socket_io_client: ^2.0.3+1
  
  # Location Services - ESSENTIAL for sports tracking
  geolocator: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
